package com.kun.keep.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.kun.keep.keep.bean.DBdKeepData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DBD_KEEP_DATA".
*/
public class DBdKeepDataDao extends AbstractDao<DBdKeepData, Long> {

    public static final String TABLENAME = "DBD_KEEP_DATA";

    /**
     * Properties of entity DBdKeepData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Distance = new Property(1, float.class, "distance", false, "DISTANCE");
        public final static Property Lat = new Property(2, double.class, "lat", false, "LAT");
        public final static Property Lng = new Property(3, double.class, "lng", false, "LNG");
    }


    public DBdKeepDataDao(DaoConfig config) {
        super(config);
    }
    
    public DBdKeepDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DBD_KEEP_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DISTANCE\" REAL NOT NULL ," + // 1: distance
                "\"LAT\" REAL NOT NULL ," + // 2: lat
                "\"LNG\" REAL NOT NULL );"); // 3: lng
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DBD_KEEP_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DBdKeepData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindDouble(2, entity.getDistance());
        stmt.bindDouble(3, entity.getLat());
        stmt.bindDouble(4, entity.getLng());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DBdKeepData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindDouble(2, entity.getDistance());
        stmt.bindDouble(3, entity.getLat());
        stmt.bindDouble(4, entity.getLng());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DBdKeepData readEntity(Cursor cursor, int offset) {
        DBdKeepData entity = new DBdKeepData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getFloat(offset + 1), // distance
            cursor.getDouble(offset + 2), // lat
            cursor.getDouble(offset + 3) // lng
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DBdKeepData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDistance(cursor.getFloat(offset + 1));
        entity.setLat(cursor.getDouble(offset + 2));
        entity.setLng(cursor.getDouble(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DBdKeepData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DBdKeepData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DBdKeepData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
